# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_interface/Body.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_interface.msg
import std_msgs.msg

class Body(genpy.Message):
  _md5sum = "b3816a053eac0ba3ff3d35c3b3a7032d"
  _type = "ros_interface/Body"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header   header     #  
uint32   id     # #人体ID
int32   type     # #人物类别，TYPE=0//未知，TYPE=1//主人，TYPE=2//指定用户，TYPE=3//其他用户 
int32   sub_type     # #人物子类别，SUB_TYPE=0//未识别，SUB_TYPE=1//成年人，SUB_TYPE=2//儿童，SUB_TYPE=3//老人
float32   confidence     # #置信度
int32   posture_type     # #人体姿态类型，POSTURE_TYPE=0//未知姿态，POSTURE_TYPE=1//站，POSTURE_TYPE=2//坐，POSTURE_TYPE=3//躺
Point3D   center_point_abs     # 在世界坐标系下的人体中心点位置
float32   theta     # #在世界坐标系下人体的朝向
float32   length     # #人体长度
float32   width     # #人体宽度
float32   height     # #人体高度
Point3D[] polygon_point_abs # # 世界坐标系下人体3D框点坐标
Point3D   velocity     # #在世界坐标系下的人体速度

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ros_interface/Point3D
float32   x     #  
float32   y     #  
float32   z     #  
"""
  __slots__ = ['header','id','type','sub_type','confidence','posture_type','center_point_abs','theta','length','width','height','polygon_point_abs','velocity']
  _slot_types = ['std_msgs/Header','uint32','int32','int32','float32','int32','ros_interface/Point3D','float32','float32','float32','float32','ros_interface/Point3D[]','ros_interface/Point3D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,type,sub_type,confidence,posture_type,center_point_abs,theta,length,width,height,polygon_point_abs,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Body, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.type is None:
        self.type = 0
      if self.sub_type is None:
        self.sub_type = 0
      if self.confidence is None:
        self.confidence = 0.
      if self.posture_type is None:
        self.posture_type = 0
      if self.center_point_abs is None:
        self.center_point_abs = ros_interface.msg.Point3D()
      if self.theta is None:
        self.theta = 0.
      if self.length is None:
        self.length = 0.
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.polygon_point_abs is None:
        self.polygon_point_abs = []
      if self.velocity is None:
        self.velocity = ros_interface.msg.Point3D()
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.type = 0
      self.sub_type = 0
      self.confidence = 0.
      self.posture_type = 0
      self.center_point_abs = ros_interface.msg.Point3D()
      self.theta = 0.
      self.length = 0.
      self.width = 0.
      self.height = 0.
      self.polygon_point_abs = []
      self.velocity = ros_interface.msg.Point3D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I2ifi7f().pack(_x.id, _x.type, _x.sub_type, _x.confidence, _x.posture_type, _x.center_point_abs.x, _x.center_point_abs.y, _x.center_point_abs.z, _x.theta, _x.length, _x.width, _x.height))
      length = len(self.polygon_point_abs)
      buff.write(_struct_I.pack(length))
      for val1 in self.polygon_point_abs:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3f().pack(_x.velocity.x, _x.velocity.y, _x.velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.center_point_abs is None:
        self.center_point_abs = ros_interface.msg.Point3D()
      if self.polygon_point_abs is None:
        self.polygon_point_abs = None
      if self.velocity is None:
        self.velocity = ros_interface.msg.Point3D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.id, _x.type, _x.sub_type, _x.confidence, _x.posture_type, _x.center_point_abs.x, _x.center_point_abs.y, _x.center_point_abs.z, _x.theta, _x.length, _x.width, _x.height,) = _get_struct_I2ifi7f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.polygon_point_abs = []
      for i in range(0, length):
        val1 = ros_interface.msg.Point3D()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.polygon_point_abs.append(val1)
      _x = self
      start = end
      end += 12
      (_x.velocity.x, _x.velocity.y, _x.velocity.z,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I2ifi7f().pack(_x.id, _x.type, _x.sub_type, _x.confidence, _x.posture_type, _x.center_point_abs.x, _x.center_point_abs.y, _x.center_point_abs.z, _x.theta, _x.length, _x.width, _x.height))
      length = len(self.polygon_point_abs)
      buff.write(_struct_I.pack(length))
      for val1 in self.polygon_point_abs:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3f().pack(_x.velocity.x, _x.velocity.y, _x.velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.center_point_abs is None:
        self.center_point_abs = ros_interface.msg.Point3D()
      if self.polygon_point_abs is None:
        self.polygon_point_abs = None
      if self.velocity is None:
        self.velocity = ros_interface.msg.Point3D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.id, _x.type, _x.sub_type, _x.confidence, _x.posture_type, _x.center_point_abs.x, _x.center_point_abs.y, _x.center_point_abs.z, _x.theta, _x.length, _x.width, _x.height,) = _get_struct_I2ifi7f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.polygon_point_abs = []
      for i in range(0, length):
        val1 = ros_interface.msg.Point3D()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.polygon_point_abs.append(val1)
      _x = self
      start = end
      end += 12
      (_x.velocity.x, _x.velocity.y, _x.velocity.z,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_I2ifi7f = None
def _get_struct_I2ifi7f():
    global _struct_I2ifi7f
    if _struct_I2ifi7f is None:
        _struct_I2ifi7f = struct.Struct("<I2ifi7f")
    return _struct_I2ifi7f
