# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_interface/FusedLocalization.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_interface.msg
import std_msgs.msg

class FusedLocalization(genpy.Message):
  _md5sum = "bda9fd4dd99802b8fbac3adb5d1dc90b"
  _type = "ros_interface/FusedLocalization"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header   header     #  
PointLLH   position     # # 经纬度高程
float32   pitch     # # 姿态角(单位弧度，满足右手定则)
float32   roll     #  
float32   heading     #  
Point3D   linear_velocity     # # 线速度（m/s，xxx坐标系）
Point3D   linear_acceleration     # # 线加速度（m/s2，xxx坐标系）
Point3D   angular_velocity     # # 角速度（度/s，xxx坐标系，满足右手定则）
int32   odom_type     # # 融合标志:0-(纯gps) 1-(gps+imu递推) 2-(语义匹配定位) 3-(语义匹配+imu+gps)
string   location_valid_flag     # # Location有效性标志位0: invalid； 1: valid
float32   origin_lat     # # 参考点纬度 GCJ-02格式
float32   origin_lon     # # 参考点经度 GCJ-02格式
PointENU   utm_position     # # 相对参考点xyz坐标
Point3D   position_std_dev     # # 位置标准差
Point3D   orientation_std_dev     # # 方向标准差
Point3D   linear_velocity_std_dev     # # 速度标准差
Point3D   linear_acceleration_std_dev     # # 加速度标准差
Point3D   angular_velocity_std_dev     # # 角速度标准差

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ros_interface/PointLLH
float32   lon     # # Longitude in degrees, ranging from -180 to 180.
float32   lat     # # Latitude in degrees, ranging from -90 to 90.
float32   height     # # WGS-84 ellipsoid height in meters.

================================================================================
MSG: ros_interface/Point3D
float32   x     #  
float32   y     #  
float32   z     #  

================================================================================
MSG: ros_interface/PointENU
float32   x     #  
float32   y     #  
float32   z     #  
"""
  __slots__ = ['header','position','pitch','roll','heading','linear_velocity','linear_acceleration','angular_velocity','odom_type','location_valid_flag','origin_lat','origin_lon','utm_position','position_std_dev','orientation_std_dev','linear_velocity_std_dev','linear_acceleration_std_dev','angular_velocity_std_dev']
  _slot_types = ['std_msgs/Header','ros_interface/PointLLH','float32','float32','float32','ros_interface/Point3D','ros_interface/Point3D','ros_interface/Point3D','int32','string','float32','float32','ros_interface/PointENU','ros_interface/Point3D','ros_interface/Point3D','ros_interface/Point3D','ros_interface/Point3D','ros_interface/Point3D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,position,pitch,roll,heading,linear_velocity,linear_acceleration,angular_velocity,odom_type,location_valid_flag,origin_lat,origin_lon,utm_position,position_std_dev,orientation_std_dev,linear_velocity_std_dev,linear_acceleration_std_dev,angular_velocity_std_dev

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FusedLocalization, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = ros_interface.msg.PointLLH()
      if self.pitch is None:
        self.pitch = 0.
      if self.roll is None:
        self.roll = 0.
      if self.heading is None:
        self.heading = 0.
      if self.linear_velocity is None:
        self.linear_velocity = ros_interface.msg.Point3D()
      if self.linear_acceleration is None:
        self.linear_acceleration = ros_interface.msg.Point3D()
      if self.angular_velocity is None:
        self.angular_velocity = ros_interface.msg.Point3D()
      if self.odom_type is None:
        self.odom_type = 0
      if self.location_valid_flag is None:
        self.location_valid_flag = ''
      if self.origin_lat is None:
        self.origin_lat = 0.
      if self.origin_lon is None:
        self.origin_lon = 0.
      if self.utm_position is None:
        self.utm_position = ros_interface.msg.PointENU()
      if self.position_std_dev is None:
        self.position_std_dev = ros_interface.msg.Point3D()
      if self.orientation_std_dev is None:
        self.orientation_std_dev = ros_interface.msg.Point3D()
      if self.linear_velocity_std_dev is None:
        self.linear_velocity_std_dev = ros_interface.msg.Point3D()
      if self.linear_acceleration_std_dev is None:
        self.linear_acceleration_std_dev = ros_interface.msg.Point3D()
      if self.angular_velocity_std_dev is None:
        self.angular_velocity_std_dev = ros_interface.msg.Point3D()
    else:
      self.header = std_msgs.msg.Header()
      self.position = ros_interface.msg.PointLLH()
      self.pitch = 0.
      self.roll = 0.
      self.heading = 0.
      self.linear_velocity = ros_interface.msg.Point3D()
      self.linear_acceleration = ros_interface.msg.Point3D()
      self.angular_velocity = ros_interface.msg.Point3D()
      self.odom_type = 0
      self.location_valid_flag = ''
      self.origin_lat = 0.
      self.origin_lon = 0.
      self.utm_position = ros_interface.msg.PointENU()
      self.position_std_dev = ros_interface.msg.Point3D()
      self.orientation_std_dev = ros_interface.msg.Point3D()
      self.linear_velocity_std_dev = ros_interface.msg.Point3D()
      self.linear_acceleration_std_dev = ros_interface.msg.Point3D()
      self.angular_velocity_std_dev = ros_interface.msg.Point3D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15fi().pack(_x.position.lon, _x.position.lat, _x.position.height, _x.pitch, _x.roll, _x.heading, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.odom_type))
      _x = self.location_valid_flag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_20f().pack(_x.origin_lat, _x.origin_lon, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.position_std_dev.x, _x.position_std_dev.y, _x.position_std_dev.z, _x.orientation_std_dev.x, _x.orientation_std_dev.y, _x.orientation_std_dev.z, _x.linear_velocity_std_dev.x, _x.linear_velocity_std_dev.y, _x.linear_velocity_std_dev.z, _x.linear_acceleration_std_dev.x, _x.linear_acceleration_std_dev.y, _x.linear_acceleration_std_dev.z, _x.angular_velocity_std_dev.x, _x.angular_velocity_std_dev.y, _x.angular_velocity_std_dev.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = ros_interface.msg.PointLLH()
      if self.linear_velocity is None:
        self.linear_velocity = ros_interface.msg.Point3D()
      if self.linear_acceleration is None:
        self.linear_acceleration = ros_interface.msg.Point3D()
      if self.angular_velocity is None:
        self.angular_velocity = ros_interface.msg.Point3D()
      if self.utm_position is None:
        self.utm_position = ros_interface.msg.PointENU()
      if self.position_std_dev is None:
        self.position_std_dev = ros_interface.msg.Point3D()
      if self.orientation_std_dev is None:
        self.orientation_std_dev = ros_interface.msg.Point3D()
      if self.linear_velocity_std_dev is None:
        self.linear_velocity_std_dev = ros_interface.msg.Point3D()
      if self.linear_acceleration_std_dev is None:
        self.linear_acceleration_std_dev = ros_interface.msg.Point3D()
      if self.angular_velocity_std_dev is None:
        self.angular_velocity_std_dev = ros_interface.msg.Point3D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.position.lon, _x.position.lat, _x.position.height, _x.pitch, _x.roll, _x.heading, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.odom_type,) = _get_struct_15fi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.location_valid_flag = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.location_valid_flag = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.origin_lat, _x.origin_lon, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.position_std_dev.x, _x.position_std_dev.y, _x.position_std_dev.z, _x.orientation_std_dev.x, _x.orientation_std_dev.y, _x.orientation_std_dev.z, _x.linear_velocity_std_dev.x, _x.linear_velocity_std_dev.y, _x.linear_velocity_std_dev.z, _x.linear_acceleration_std_dev.x, _x.linear_acceleration_std_dev.y, _x.linear_acceleration_std_dev.z, _x.angular_velocity_std_dev.x, _x.angular_velocity_std_dev.y, _x.angular_velocity_std_dev.z,) = _get_struct_20f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_15fi().pack(_x.position.lon, _x.position.lat, _x.position.height, _x.pitch, _x.roll, _x.heading, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.odom_type))
      _x = self.location_valid_flag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_20f().pack(_x.origin_lat, _x.origin_lon, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.position_std_dev.x, _x.position_std_dev.y, _x.position_std_dev.z, _x.orientation_std_dev.x, _x.orientation_std_dev.y, _x.orientation_std_dev.z, _x.linear_velocity_std_dev.x, _x.linear_velocity_std_dev.y, _x.linear_velocity_std_dev.z, _x.linear_acceleration_std_dev.x, _x.linear_acceleration_std_dev.y, _x.linear_acceleration_std_dev.z, _x.angular_velocity_std_dev.x, _x.angular_velocity_std_dev.y, _x.angular_velocity_std_dev.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.position is None:
        self.position = ros_interface.msg.PointLLH()
      if self.linear_velocity is None:
        self.linear_velocity = ros_interface.msg.Point3D()
      if self.linear_acceleration is None:
        self.linear_acceleration = ros_interface.msg.Point3D()
      if self.angular_velocity is None:
        self.angular_velocity = ros_interface.msg.Point3D()
      if self.utm_position is None:
        self.utm_position = ros_interface.msg.PointENU()
      if self.position_std_dev is None:
        self.position_std_dev = ros_interface.msg.Point3D()
      if self.orientation_std_dev is None:
        self.orientation_std_dev = ros_interface.msg.Point3D()
      if self.linear_velocity_std_dev is None:
        self.linear_velocity_std_dev = ros_interface.msg.Point3D()
      if self.linear_acceleration_std_dev is None:
        self.linear_acceleration_std_dev = ros_interface.msg.Point3D()
      if self.angular_velocity_std_dev is None:
        self.angular_velocity_std_dev = ros_interface.msg.Point3D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.position.lon, _x.position.lat, _x.position.height, _x.pitch, _x.roll, _x.heading, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.odom_type,) = _get_struct_15fi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.location_valid_flag = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.location_valid_flag = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.origin_lat, _x.origin_lon, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.position_std_dev.x, _x.position_std_dev.y, _x.position_std_dev.z, _x.orientation_std_dev.x, _x.orientation_std_dev.y, _x.orientation_std_dev.z, _x.linear_velocity_std_dev.x, _x.linear_velocity_std_dev.y, _x.linear_velocity_std_dev.z, _x.linear_acceleration_std_dev.x, _x.linear_acceleration_std_dev.y, _x.linear_acceleration_std_dev.z, _x.angular_velocity_std_dev.x, _x.angular_velocity_std_dev.y, _x.angular_velocity_std_dev.z,) = _get_struct_20f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_15fi = None
def _get_struct_15fi():
    global _struct_15fi
    if _struct_15fi is None:
        _struct_15fi = struct.Struct("<15fi")
    return _struct_15fi
_struct_20f = None
def _get_struct_20f():
    global _struct_20f
    if _struct_20f is None:
        _struct_20f = struct.Struct("<20f")
    return _struct_20f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
