# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_interface/OccGrid.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class OccGrid(genpy.Message):
  _md5sum = "44aafbeacd0b2f46dbacbb6fc274af9e"
  _type = "ros_interface/OccGrid"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32   type     # //网格类型，TYPE=0//未知，TYPE=1//可行驶，TYPE=2//不可行驶
int32   index_x     # //网格横向编号
int32   index_y     # //网格纵向编号
int32   index_z     # //网格垂直方向编号
float32   grid_size_x     # //网格横向大小，单位：米
float32   grid_size_y     # //网格纵向大小，单位：米
float32   grid_size_z     # //网格垂直方向大小，单位：米
"""
  __slots__ = ['type','index_x','index_y','index_z','grid_size_x','grid_size_y','grid_size_z']
  _slot_types = ['int32','int32','int32','int32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,index_x,index_y,index_z,grid_size_x,grid_size_y,grid_size_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OccGrid, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = 0
      if self.index_x is None:
        self.index_x = 0
      if self.index_y is None:
        self.index_y = 0
      if self.index_z is None:
        self.index_z = 0
      if self.grid_size_x is None:
        self.grid_size_x = 0.
      if self.grid_size_y is None:
        self.grid_size_y = 0.
      if self.grid_size_z is None:
        self.grid_size_z = 0.
    else:
      self.type = 0
      self.index_x = 0
      self.index_y = 0
      self.index_z = 0
      self.grid_size_x = 0.
      self.grid_size_y = 0.
      self.grid_size_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i3f().pack(_x.type, _x.index_x, _x.index_y, _x.index_z, _x.grid_size_x, _x.grid_size_y, _x.grid_size_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.type, _x.index_x, _x.index_y, _x.index_z, _x.grid_size_x, _x.grid_size_y, _x.grid_size_z,) = _get_struct_4i3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i3f().pack(_x.type, _x.index_x, _x.index_y, _x.index_z, _x.grid_size_x, _x.grid_size_y, _x.grid_size_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.type, _x.index_x, _x.index_y, _x.index_z, _x.grid_size_x, _x.grid_size_y, _x.grid_size_z,) = _get_struct_4i3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i3f = None
def _get_struct_4i3f():
    global _struct_4i3f
    if _struct_4i3f is None:
        _struct_4i3f = struct.Struct("<4i3f")
    return _struct_4i3f
