(cl:in-package ros_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          IS_VALID-VAL
          IS_VALID
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ELEVATION-VAL
          ELEVATION
          UTM_POSITION-VAL
          UTM_POSITION
          ATTITUDE-VAL
          ATTITUDE
          SD_POSITION-VAL
          SD_POSITION
          SD_VELOCITY-VAL
          SD_VELOCITY
          SD_ATTITUDE-VAL
          SD_ATTITUDE
          SECOND-VAL
          SECOND
          SAT_USE_NUM-VAL
          SAT_USE_NUM
          SAT_IN_VIEW_NUM-VAL
          SAT_IN_VIEW_NUM
          SOLUTION_STATUS-VAL
          SOLUTION_STATUS
          POSITION_TYPE-VAL
          POSITION_TYPE
          LINEAR_VELOCITY-VAL
          LINEAR_VELOCITY
))