// Generated by gencpp from file ros_interface/FaceList.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_FACELIST_H
#define ROS_INTERFACE_MESSAGE_FACELIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/Face.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct FaceList_
{
  typedef FaceList_<ContainerAllocator> Type;

  FaceList_()
    : header()
    , face()  {
    }
  FaceList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , face(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ros_interface::Face_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_interface::Face_<ContainerAllocator> >> _face_type;
  _face_type face;





  typedef boost::shared_ptr< ::ros_interface::FaceList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::FaceList_<ContainerAllocator> const> ConstPtr;

}; // struct FaceList_

typedef ::ros_interface::FaceList_<std::allocator<void> > FaceList;

typedef boost::shared_ptr< ::ros_interface::FaceList > FaceListPtr;
typedef boost::shared_ptr< ::ros_interface::FaceList const> FaceListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::FaceList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::FaceList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::FaceList_<ContainerAllocator1> & lhs, const ::ros_interface::FaceList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.face == rhs.face;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::FaceList_<ContainerAllocator1> & lhs, const ::ros_interface::FaceList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::FaceList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::FaceList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::FaceList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::FaceList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::FaceList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::FaceList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::FaceList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95adfebc50f00fb22ca152865b53b267";
  }

  static const char* value(const ::ros_interface::FaceList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95adfebc50f00fb2ULL;
  static const uint64_t static_value2 = 0x2ca152865b53b267ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::FaceList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/FaceList";
  }

  static const char* value(const ::ros_interface::FaceList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::FaceList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     #  \n"
"Face[]  face   #感知的所有人体信息\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Face\n"
"Header   header     #  \n"
"uint32   id     # #面容ID\n"
"string   name     # #面容名称\n"
"int32   emotion_type     # #情绪类别，EMOTION_TYPE=0//未知，EMOTION_TYPE=1//开心，EMOTION_TYPE=2//悲伤\n"
"int32   type     # #人物类别，TYPE=0//未知，TYPE=1//主人，TYPE=2//指定主人，TYPE=3//陌生用户\n"
"float32   confidence     # #人脸检测置信度\n"
"BBox2D   face_box     # # 人脸图像框\n"
"BBox2D   body_box     # # 人体图像框\n"
"Point3D   center_point_abs     # 在世界坐标系下的人体中心点位置\n"
"sensor_msgs/Image image\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/BBox2D\n"
"int16   xmin     # # 图像框左上角的x坐标\n"
"int16   ymin     # # 图像框左上角的y坐标\n"
"int16   xmax     # # 图像框右下角的x坐标\n"
"int16   ymax     # # 图像框右下角的y坐标\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Point3D\n"
"float32   x     #  \n"
"float32   y     #  \n"
"float32   z     #  \n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::ros_interface::FaceList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::FaceList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.face);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::FaceList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::FaceList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "face[]" << std::endl;
    for (size_t i = 0; i < v.face.size(); ++i)
    {
      s << indent << "  face[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_interface::Face_<ContainerAllocator> >::stream(s, indent + "    ", v.face[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_FACELIST_H
