// Generated by gencpp from file ros_interface/FreeSpace.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_FREESPACE_H
#define ROS_INTERFACE_MESSAGE_FREESPACE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/OccGrid.h>
#include <ros_interface/Point3D.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct FreeSpace_
{
  typedef FreeSpace_<ContainerAllocator> Type;

  FreeSpace_()
    : header()
    , freegrids()
    , freespace_region()  {
    }
  FreeSpace_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , freegrids(_alloc)
    , freespace_region(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ros_interface::OccGrid_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_interface::OccGrid_<ContainerAllocator> >> _freegrids_type;
  _freegrids_type freegrids;

   typedef std::vector< ::ros_interface::Point3D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_interface::Point3D_<ContainerAllocator> >> _freespace_region_type;
  _freespace_region_type freespace_region;





  typedef boost::shared_ptr< ::ros_interface::FreeSpace_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::FreeSpace_<ContainerAllocator> const> ConstPtr;

}; // struct FreeSpace_

typedef ::ros_interface::FreeSpace_<std::allocator<void> > FreeSpace;

typedef boost::shared_ptr< ::ros_interface::FreeSpace > FreeSpacePtr;
typedef boost::shared_ptr< ::ros_interface::FreeSpace const> FreeSpaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::FreeSpace_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::FreeSpace_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::FreeSpace_<ContainerAllocator1> & lhs, const ::ros_interface::FreeSpace_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.freegrids == rhs.freegrids &&
    lhs.freespace_region == rhs.freespace_region;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::FreeSpace_<ContainerAllocator1> & lhs, const ::ros_interface::FreeSpace_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::FreeSpace_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::FreeSpace_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::FreeSpace_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::FreeSpace_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::FreeSpace_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::FreeSpace_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::FreeSpace_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15506d871fb0214f52a0519b30282177";
  }

  static const char* value(const ::ros_interface::FreeSpace_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15506d871fb0214fULL;
  static const uint64_t static_value2 = 0x52a0519b30282177ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::FreeSpace_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/FreeSpace";
  }

  static const char* value(const ::ros_interface::FreeSpace_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::FreeSpace_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     # //网格类型，TYPE=0//未知，TYPE=1//可行驶，TYPE=2//不可行驶\n"
"OccGrid[] freegrids # //网格横向编号\n"
"#Polygon3D[] freegrids\n"
"Point3D[] freespace_region # //网格大小，单位：米\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/OccGrid\n"
"int32   type     # //网格类型，TYPE=0//未知，TYPE=1//可行驶，TYPE=2//不可行驶\n"
"int32   index_x     # //网格横向编号\n"
"int32   index_y     # //网格纵向编号\n"
"int32   index_z     # //网格垂直方向编号\n"
"float32   grid_size_x     # //网格横向大小，单位：米\n"
"float32   grid_size_y     # //网格纵向大小，单位：米\n"
"float32   grid_size_z     # //网格垂直方向大小，单位：米\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Point3D\n"
"float32   x     #  \n"
"float32   y     #  \n"
"float32   z     #  \n"
;
  }

  static const char* value(const ::ros_interface::FreeSpace_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::FreeSpace_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.freegrids);
      stream.next(m.freespace_region);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FreeSpace_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::FreeSpace_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::FreeSpace_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "freegrids[]" << std::endl;
    for (size_t i = 0; i < v.freegrids.size(); ++i)
    {
      s << indent << "  freegrids[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_interface::OccGrid_<ContainerAllocator> >::stream(s, indent + "    ", v.freegrids[i]);
    }
    s << indent << "freespace_region[]" << std::endl;
    for (size_t i = 0; i < v.freespace_region.size(); ++i)
    {
      s << indent << "  freespace_region[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "    ", v.freespace_region[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_FREESPACE_H
