// Generated by gencpp from file ros_interface/FusedLocalization.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_FUSEDLOCALIZATION_H
#define ROS_INTERFACE_MESSAGE_FUSEDLOCALIZATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/PointLLH.h>
#include <ros_interface/Point3D.h>
#include <ros_interface/Point3D.h>
#include <ros_interface/Point3D.h>
#include <ros_interface/PointENU.h>
#include <ros_interface/Point3D.h>
#include <ros_interface/Point3D.h>
#include <ros_interface/Point3D.h>
#include <ros_interface/Point3D.h>
#include <ros_interface/Point3D.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct FusedLocalization_
{
  typedef FusedLocalization_<ContainerAllocator> Type;

  FusedLocalization_()
    : header()
    , position()
    , pitch(0.0)
    , roll(0.0)
    , heading(0.0)
    , linear_velocity()
    , linear_acceleration()
    , angular_velocity()
    , odom_type(0)
    , location_valid_flag()
    , origin_lat(0.0)
    , origin_lon(0.0)
    , utm_position()
    , position_std_dev()
    , orientation_std_dev()
    , linear_velocity_std_dev()
    , linear_acceleration_std_dev()
    , angular_velocity_std_dev()  {
    }
  FusedLocalization_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , pitch(0.0)
    , roll(0.0)
    , heading(0.0)
    , linear_velocity(_alloc)
    , linear_acceleration(_alloc)
    , angular_velocity(_alloc)
    , odom_type(0)
    , location_valid_flag(_alloc)
    , origin_lat(0.0)
    , origin_lon(0.0)
    , utm_position(_alloc)
    , position_std_dev(_alloc)
    , orientation_std_dev(_alloc)
    , linear_velocity_std_dev(_alloc)
    , linear_acceleration_std_dev(_alloc)
    , angular_velocity_std_dev(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ros_interface::PointLLH_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _heading_type;
  _heading_type heading;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef int32_t _odom_type_type;
  _odom_type_type odom_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _location_valid_flag_type;
  _location_valid_flag_type location_valid_flag;

   typedef float _origin_lat_type;
  _origin_lat_type origin_lat;

   typedef float _origin_lon_type;
  _origin_lon_type origin_lon;

   typedef  ::ros_interface::PointENU_<ContainerAllocator>  _utm_position_type;
  _utm_position_type utm_position;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _position_std_dev_type;
  _position_std_dev_type position_std_dev;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _orientation_std_dev_type;
  _orientation_std_dev_type orientation_std_dev;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _linear_velocity_std_dev_type;
  _linear_velocity_std_dev_type linear_velocity_std_dev;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _linear_acceleration_std_dev_type;
  _linear_acceleration_std_dev_type linear_acceleration_std_dev;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _angular_velocity_std_dev_type;
  _angular_velocity_std_dev_type angular_velocity_std_dev;





  typedef boost::shared_ptr< ::ros_interface::FusedLocalization_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::FusedLocalization_<ContainerAllocator> const> ConstPtr;

}; // struct FusedLocalization_

typedef ::ros_interface::FusedLocalization_<std::allocator<void> > FusedLocalization;

typedef boost::shared_ptr< ::ros_interface::FusedLocalization > FusedLocalizationPtr;
typedef boost::shared_ptr< ::ros_interface::FusedLocalization const> FusedLocalizationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::FusedLocalization_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::FusedLocalization_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::FusedLocalization_<ContainerAllocator1> & lhs, const ::ros_interface::FusedLocalization_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.heading == rhs.heading &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.odom_type == rhs.odom_type &&
    lhs.location_valid_flag == rhs.location_valid_flag &&
    lhs.origin_lat == rhs.origin_lat &&
    lhs.origin_lon == rhs.origin_lon &&
    lhs.utm_position == rhs.utm_position &&
    lhs.position_std_dev == rhs.position_std_dev &&
    lhs.orientation_std_dev == rhs.orientation_std_dev &&
    lhs.linear_velocity_std_dev == rhs.linear_velocity_std_dev &&
    lhs.linear_acceleration_std_dev == rhs.linear_acceleration_std_dev &&
    lhs.angular_velocity_std_dev == rhs.angular_velocity_std_dev;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::FusedLocalization_<ContainerAllocator1> & lhs, const ::ros_interface::FusedLocalization_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::FusedLocalization_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::FusedLocalization_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::FusedLocalization_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::FusedLocalization_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::FusedLocalization_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::FusedLocalization_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::FusedLocalization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bda9fd4dd99802b8fbac3adb5d1dc90b";
  }

  static const char* value(const ::ros_interface::FusedLocalization_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbda9fd4dd99802b8ULL;
  static const uint64_t static_value2 = 0xfbac3adb5d1dc90bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::FusedLocalization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/FusedLocalization";
  }

  static const char* value(const ::ros_interface::FusedLocalization_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::FusedLocalization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     #  \n"
"PointLLH   position     # # 经纬度高程\n"
"float32   pitch     # # 姿态角(单位弧度，满足右手定则)\n"
"float32   roll     #  \n"
"float32   heading     #  \n"
"Point3D   linear_velocity     # # 线速度（m/s，xxx坐标系）\n"
"Point3D   linear_acceleration     # # 线加速度（m/s2，xxx坐标系）\n"
"Point3D   angular_velocity     # # 角速度（度/s，xxx坐标系，满足右手定则）\n"
"int32   odom_type     # # 融合标志:0-(纯gps) 1-(gps+imu递推) 2-(语义匹配定位) 3-(语义匹配+imu+gps)\n"
"string   location_valid_flag     # # Location有效性标志位0: invalid； 1: valid\n"
"float32   origin_lat     # # 参考点纬度 GCJ-02格式\n"
"float32   origin_lon     # # 参考点经度 GCJ-02格式\n"
"PointENU   utm_position     # # 相对参考点xyz坐标\n"
"Point3D   position_std_dev     # # 位置标准差\n"
"Point3D   orientation_std_dev     # # 方向标准差\n"
"Point3D   linear_velocity_std_dev     # # 速度标准差\n"
"Point3D   linear_acceleration_std_dev     # # 加速度标准差\n"
"Point3D   angular_velocity_std_dev     # # 角速度标准差\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/PointLLH\n"
"float32   lon     # # Longitude in degrees, ranging from -180 to 180.\n"
"float32   lat     # # Latitude in degrees, ranging from -90 to 90.\n"
"float32   height     # # WGS-84 ellipsoid height in meters.\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Point3D\n"
"float32   x     #  \n"
"float32   y     #  \n"
"float32   z     #  \n"
"\n"
"================================================================================\n"
"MSG: ros_interface/PointENU\n"
"float32   x     #  \n"
"float32   y     #  \n"
"float32   z     #  \n"
;
  }

  static const char* value(const ::ros_interface::FusedLocalization_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::FusedLocalization_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.heading);
      stream.next(m.linear_velocity);
      stream.next(m.linear_acceleration);
      stream.next(m.angular_velocity);
      stream.next(m.odom_type);
      stream.next(m.location_valid_flag);
      stream.next(m.origin_lat);
      stream.next(m.origin_lon);
      stream.next(m.utm_position);
      stream.next(m.position_std_dev);
      stream.next(m.orientation_std_dev);
      stream.next(m.linear_velocity_std_dev);
      stream.next(m.linear_acceleration_std_dev);
      stream.next(m.angular_velocity_std_dev);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FusedLocalization_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::FusedLocalization_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::FusedLocalization_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::ros_interface::PointLLH_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    s << indent << "linear_velocity: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "odom_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.odom_type);
    s << indent << "location_valid_flag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.location_valid_flag);
    s << indent << "origin_lat: ";
    Printer<float>::stream(s, indent + "  ", v.origin_lat);
    s << indent << "origin_lon: ";
    Printer<float>::stream(s, indent + "  ", v.origin_lon);
    s << indent << "utm_position: ";
    s << std::endl;
    Printer< ::ros_interface::PointENU_<ContainerAllocator> >::stream(s, indent + "  ", v.utm_position);
    s << indent << "position_std_dev: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.position_std_dev);
    s << indent << "orientation_std_dev: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation_std_dev);
    s << indent << "linear_velocity_std_dev: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_velocity_std_dev);
    s << indent << "linear_acceleration_std_dev: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration_std_dev);
    s << indent << "angular_velocity_std_dev: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity_std_dev);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_FUSEDLOCALIZATION_H
