// Generated by gencpp from file ros_interface/Obstacle.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_OBSTACLE_H
#define ROS_INTERFACE_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/Point3D.h>
#include <ros_interface/Point3D.h>
#include <ros_interface/OccGrid.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct Obstacle_
{
  typedef Obstacle_<ContainerAllocator> Type;

  Obstacle_()
    : header()
    , id(0)
    , type(0)
    , confidence(0.0)
    , center_point_abs()
    , theta(0.0)
    , velocity()
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , occupy_grid()  {
    }
  Obstacle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , type(0)
    , confidence(0.0)
    , center_point_abs(_alloc)
    , theta(0.0)
    , velocity(_alloc)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , occupy_grid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _id_type;
  _id_type id;

   typedef int32_t _type_type;
  _type_type type;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _center_point_abs_type;
  _center_point_abs_type center_point_abs;

   typedef float _theta_type;
  _theta_type theta;

   typedef  ::ros_interface::Point3D_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef float _length_type;
  _length_type length;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef std::vector< ::ros_interface::OccGrid_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_interface::OccGrid_<ContainerAllocator> >> _occupy_grid_type;
  _occupy_grid_type occupy_grid;





  typedef boost::shared_ptr< ::ros_interface::Obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::Obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacle_

typedef ::ros_interface::Obstacle_<std::allocator<void> > Obstacle;

typedef boost::shared_ptr< ::ros_interface::Obstacle > ObstaclePtr;
typedef boost::shared_ptr< ::ros_interface::Obstacle const> ObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::Obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::Obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::Obstacle_<ContainerAllocator1> & lhs, const ::ros_interface::Obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.confidence == rhs.confidence &&
    lhs.center_point_abs == rhs.center_point_abs &&
    lhs.theta == rhs.theta &&
    lhs.velocity == rhs.velocity &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.occupy_grid == rhs.occupy_grid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::Obstacle_<ContainerAllocator1> & lhs, const ::ros_interface::Obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::Obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::Obstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::Obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::Obstacle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cdacb9dc63898edc5f02d22321631b6";
  }

  static const char* value(const ::ros_interface::Obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cdacb9dc63898edULL;
  static const uint64_t static_value2 = 0xc5f02d22321631b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/Obstacle";
  }

  static const char* value(const ::ros_interface::Obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::Obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     #  \n"
"uint8   id     # #物体ID\n"
"int32   type     # #物体类型，TYPE=0//未知物体，TYPE=1//门，TYPE=2//窗户，TYPE=3//冰箱，TYPE=4//电视，TYPE=5//风扇，TYPE=6//衣柜，TYPE=7//床，TYPE=8//沙发，TYPE=9//桌子，TYPE=10//椅子，TYPE=11//楼梯，TYPE=12//台阶，TYPE=13//斜坡，TYPE=14//坑洼，TYPE=15//人\n"
"float32   confidence     # #置信度\n"
"Point3D   center_point_abs     # #在世界坐标系下的物体中心位置\n"
"float32   theta     # #在世界坐标系下物体的朝向\n"
"Point3D   velocity     # #在世界坐标系下的物体的速度\n"
"float32   length     # #物体外接立体的长度\n"
"float32   width     # #物体外接立体的宽度\n"
"float32   height     # #物体外接立体的高度\n"
"OccGrid[] occupy_grid # # 世界坐标系下物体占据的网格\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Point3D\n"
"float32   x     #  \n"
"float32   y     #  \n"
"float32   z     #  \n"
"\n"
"================================================================================\n"
"MSG: ros_interface/OccGrid\n"
"int32   type     # //网格类型，TYPE=0//未知，TYPE=1//可行驶，TYPE=2//不可行驶\n"
"int32   index_x     # //网格横向编号\n"
"int32   index_y     # //网格纵向编号\n"
"int32   index_z     # //网格垂直方向编号\n"
"float32   grid_size_x     # //网格横向大小，单位：米\n"
"float32   grid_size_y     # //网格纵向大小，单位：米\n"
"float32   grid_size_z     # //网格垂直方向大小，单位：米\n"
;
  }

  static const char* value(const ::ros_interface::Obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::Obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.confidence);
      stream.next(m.center_point_abs);
      stream.next(m.theta);
      stream.next(m.velocity);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.occupy_grid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::Obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::Obstacle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "center_point_abs: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.center_point_abs);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::ros_interface::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "occupy_grid[]" << std::endl;
    for (size_t i = 0; i < v.occupy_grid.size(); ++i)
    {
      s << indent << "  occupy_grid[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_interface::OccGrid_<ContainerAllocator> >::stream(s, indent + "    ", v.occupy_grid[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_OBSTACLE_H
