// Generated by gencpp from file ros_interface/PercReq.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_PERCREQ_H
#define ROS_INTERFACE_MESSAGE_PERCREQ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct PercReq_
{
  typedef PercReq_<ContainerAllocator> Type;

  PercReq_()
    : header()
    , req_id(0)
    , perc_kind(0)
    , danger_info()  {
    }
  PercReq_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , req_id(0)
    , perc_kind(0)
    , danger_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _req_id_type;
  _req_id_type req_id;

   typedef int32_t _perc_kind_type;
  _perc_kind_type perc_kind;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _danger_info_type;
  _danger_info_type danger_info;





  typedef boost::shared_ptr< ::ros_interface::PercReq_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::PercReq_<ContainerAllocator> const> ConstPtr;

}; // struct PercReq_

typedef ::ros_interface::PercReq_<std::allocator<void> > PercReq;

typedef boost::shared_ptr< ::ros_interface::PercReq > PercReqPtr;
typedef boost::shared_ptr< ::ros_interface::PercReq const> PercReqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::PercReq_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::PercReq_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::PercReq_<ContainerAllocator1> & lhs, const ::ros_interface::PercReq_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.req_id == rhs.req_id &&
    lhs.perc_kind == rhs.perc_kind &&
    lhs.danger_info == rhs.danger_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::PercReq_<ContainerAllocator1> & lhs, const ::ros_interface::PercReq_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::PercReq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::PercReq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::PercReq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::PercReq_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::PercReq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::PercReq_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::PercReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f83aae89ae6ebffd7f2e482e5efdb166";
  }

  static const char* value(const ::ros_interface::PercReq_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf83aae89ae6ebffdULL;
  static const uint64_t static_value2 = 0x7f2e482e5efdb166ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::PercReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/PercReq";
  }

  static const char* value(const ::ros_interface::PercReq_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::PercReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     #  \n"
"uint64   req_id     # #动作执行id,增加含义：时间+序号，2024101620 0001\n"
"int32   perc_kind     # # Perception Kind 枚举类型 uint32 PERC_AUTO_CHARGING   = 20  # 自动充电 uint32 PERC_CHECK_ENV       = 21  # 环境查看 uint32 PERC_AUTO_MAPPING    = 22  # 自动建图 uint32 PERC_FOLLOW               = 30  # 跟随模式 uint32 PERC_STRANGER_WELCOME     = 31  # 陌生人迎接 uint32 PERC_OWNER_WELCOME        = 32  # 主人迎接 uint32 PERC_BEHAVIOR_INTERACTION = 33  # 行为互动 uint32 PERC_HANDSHAKE            = 34   # 握手动作 uint32 PERC_STANDBY_ACCOMPANY    = 35  # 待机陪伴 uint32 PERC_HAPPY_ACCOMPANY      = 36  # 娱乐陪伴 uint32 PERC_WORK_ACCOMPANY       = 37  # 工作陪伴 uint32 PERC_POSITIVE_ACCOMPANY   = 38  # 积极陪伴 uint32 PERC_NEGATIVE_ACCOMPANY   = 39  # 消极陪伴 uint32 PERC_CHILD_WATCH          = 40  # 小孩看护 uint32 PERC_OLDER_WATCH          = 41  # 老人看护 uint32 PERC_DANGER_REMINDER      = 42   # 危险提醒 uint32 PERC_EVENT_REMINDER       = 43  # 事件提醒 uint32 PERC_CATWALK_START        = 44  # 开始走秀 uint32 PERC_CATWALK_ACT          = 45  # 走秀互动 uint32 PERC_CATWALK_SHOW         = 46  # 走秀展示 uint32 PERC_CATWALK_BACK         = 47  # 走秀返回 uint32 PERC_FREE_TIME   = 50  # 自由活动 uint32 PERC_SOCIALIZE   = 51  # 社交模式 uint32 PERC_DANGER_INFO = 60  # 上报危险信息（不需要请求） uint32 PERC_CANCEL      = 100  # 任务取消（不需要请求） uint32 PERC_NODE_CLOSE = 200  #关闭指令 uint32 PERC_NODE_START = 201  #启动指令 uint32 PERC_NODE_RESET = 202  #重启指令\n"
"string   danger_info     # # 危险信息\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ros_interface::PercReq_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::PercReq_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.req_id);
      stream.next(m.perc_kind);
      stream.next(m.danger_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PercReq_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::PercReq_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::PercReq_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "req_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.req_id);
    s << indent << "perc_kind: ";
    Printer<int32_t>::stream(s, indent + "  ", v.perc_kind);
    s << indent << "danger_info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.danger_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_PERCREQ_H
