// Generated by gencpp from file ros_interface/PercCmd.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_PERCCMD_H
#define ROS_INTERFACE_MESSAGE_PERCCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/Point.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct PercCmd_
{
  typedef PercCmd_<ContainerAllocator> Type;

  PercCmd_()
    : header()
    , action_id(0)
    , perc_kind(0)
    , req_id(0)
    , angle(0.0)
    , point_name()
    , point()  {
    }
  PercCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , action_id(0)
    , perc_kind(0)
    , req_id(0)
    , angle(0.0)
    , point_name(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _action_id_type;
  _action_id_type action_id;

   typedef int32_t _perc_kind_type;
  _perc_kind_type perc_kind;

   typedef uint64_t _req_id_type;
  _req_id_type req_id;

   typedef float _angle_type;
  _angle_type angle;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _point_name_type;
  _point_name_type point_name;

   typedef  ::ros_interface::Point_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::ros_interface::PercCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::PercCmd_<ContainerAllocator> const> ConstPtr;

}; // struct PercCmd_

typedef ::ros_interface::PercCmd_<std::allocator<void> > PercCmd;

typedef boost::shared_ptr< ::ros_interface::PercCmd > PercCmdPtr;
typedef boost::shared_ptr< ::ros_interface::PercCmd const> PercCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::PercCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::PercCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::PercCmd_<ContainerAllocator1> & lhs, const ::ros_interface::PercCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.action_id == rhs.action_id &&
    lhs.perc_kind == rhs.perc_kind &&
    lhs.req_id == rhs.req_id &&
    lhs.angle == rhs.angle &&
    lhs.point_name == rhs.point_name &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::PercCmd_<ContainerAllocator1> & lhs, const ::ros_interface::PercCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::PercCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::PercCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::PercCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::PercCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::PercCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::PercCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::PercCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ee16e7d49b47f91bbd34c18cdee9485";
  }

  static const char* value(const ::ros_interface::PercCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ee16e7d49b47f91ULL;
  static const uint64_t static_value2 = 0xbbd34c18cdee9485ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::PercCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/PercCmd";
  }

  static const char* value(const ::ros_interface::PercCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::PercCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     #  \n"
"uint64   action_id     # #动作执行id\n"
"int32   perc_kind     # # Perception Kind 枚举类型 uint32 PERC_DEST   = 1   #点到点 uint32 PERC_ABS    = 2   #绝对位置 uint32 PERC_REL    = 3    #相对位置 uint32 PERC_AUTO_CHARGING   = 20  # 自动充电 uint32 PERC_CHECK_ENV       = 21  # 环境查看 uint32 PERC_AUTO_MAPPING    = 22  # 自动建图 uint32 PERC_FOLLOW               = 30  # 跟随模式 uint32 PERC_STRANGER_WELCOME     = 31  # 陌生人迎接 uint32 PERC_OWNER_WELCOME        = 32  # 主人迎接 uint32 PERC_BEHAVIOR_INTERACTION = 33  # 行为互动 uint32 PERC_HANDSHAKE            = 34   # 握手动作 uint32 PERC_STANDBY_ACCOMPANY    = 35  # 待机陪伴 uint32 PERC_HAPPY_ACCOMPANY      = 36  # 娱乐陪伴 uint32 PERC_WORK_ACCOMPANY       = 37  # 工作陪伴 uint32 PERC_POSITIVE_ACCOMPANY   = 38  # 积极陪伴 uint32 PERC_NEGATIVE_ACCOMPANY   = 39  # 消极陪伴 uint32 PERC_CHILD_WATCH          = 40  # 小孩看护 uint32 PERC_OLDER_WATCH          = 41  # 老人看护 uint32 PERC_DANGER_REMINDER      = 42   # 危险提醒 uint32 PERC_EVENT_REMINDER       = 43  # 事件提醒 uint32 PERC_CATWALK_START        = 44  # 开始走秀 uint32 PERC_CATWALK_ACT          = 45  # 走秀互动 uint32 PERC_CATWALK_SHOW         = 46  # 走秀展示 uint32 PERC_CATWALK_BACK         = 47  # 走秀返回 uint32 PERC_FREE_TIME   = 50  # 自由活动 uint32 PERC_SOCIALIZE   = 51  # 社交模式 uint32 PERC_DANGER_INFO = 60  # 上报危险信息（不需要请求） uint32 PERC_CANCEL      = 100  # 任务取消（不需要请求） uint32 PERC_NODE_CLOSE = 200  #关闭指令 uint32 PERC_NODE_START = 201  #启动指令 uint32 PERC_NODE_RESET = 202  #重启指令\n"
"uint64   req_id     # #发送请求的id，可以先不用管，调试使用\n"
"float32   angle     # # 语音的角度\n"
"string   point_name     # # 字符串表示某个位置（语义位置）\n"
"Point   point     # geometry_msgs/Point point  # Point表示某个位置\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Point\n"
"float32   x     #  \n"
"float32   y     #  \n"
"float32   z     #  \n"
;
  }

  static const char* value(const ::ros_interface::PercCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::PercCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.action_id);
      stream.next(m.perc_kind);
      stream.next(m.req_id);
      stream.next(m.angle);
      stream.next(m.point_name);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PercCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::PercCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::PercCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "action_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.action_id);
    s << indent << "perc_kind: ";
    Printer<int32_t>::stream(s, indent + "  ", v.perc_kind);
    s << indent << "req_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.req_id);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "point_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.point_name);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::ros_interface::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_PERCCMD_H
