// Generated by gencpp from file ros_interface/RobotEnd.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_ROBOTEND_H
#define ROS_INTERFACE_MESSAGE_ROBOTEND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/Vector3.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct RobotEnd_
{
  typedef RobotEnd_<ContainerAllocator> Type;

  RobotEnd_()
    : header()
    , is_heading(false)
    , endpoint()
    , angle(0.0)  {
    }
  RobotEnd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_heading(false)
    , endpoint(_alloc)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_heading_type;
  _is_heading_type is_heading;

   typedef  ::ros_interface::Vector3_<ContainerAllocator>  _endpoint_type;
  _endpoint_type endpoint;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::ros_interface::RobotEnd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::RobotEnd_<ContainerAllocator> const> ConstPtr;

}; // struct RobotEnd_

typedef ::ros_interface::RobotEnd_<std::allocator<void> > RobotEnd;

typedef boost::shared_ptr< ::ros_interface::RobotEnd > RobotEndPtr;
typedef boost::shared_ptr< ::ros_interface::RobotEnd const> RobotEndConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::RobotEnd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::RobotEnd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::RobotEnd_<ContainerAllocator1> & lhs, const ::ros_interface::RobotEnd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.is_heading == rhs.is_heading &&
    lhs.endpoint == rhs.endpoint &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::RobotEnd_<ContainerAllocator1> & lhs, const ::ros_interface::RobotEnd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::RobotEnd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::RobotEnd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::RobotEnd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::RobotEnd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::RobotEnd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::RobotEnd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::RobotEnd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79738a95184440d887069e7ba5c4e9d6";
  }

  static const char* value(const ::ros_interface::RobotEnd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79738a95184440d8ULL;
  static const uint64_t static_value2 = 0x87069e7ba5c4e9d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::RobotEnd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/RobotEnd";
  }

  static const char* value(const ::ros_interface::RobotEnd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::RobotEnd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     #  \n"
"bool   is_heading     # 是否是寻声导航\n"
"Vector3   endpoint     # 导航终点\n"
"float32   angle     # 寻声导航角度\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Vector3\n"
"float32   x     #  \n"
"float32   y     #  \n"
"float32   z     #  \n"
;
  }

  static const char* value(const ::ros_interface::RobotEnd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::RobotEnd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_heading);
      stream.next(m.endpoint);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotEnd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::RobotEnd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::RobotEnd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_heading: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_heading);
    s << indent << "endpoint: ";
    s << std::endl;
    Printer< ::ros_interface::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.endpoint);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_ROBOTEND_H
