// Generated by gencpp from file ros_interface/RobotPlan.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_ROBOTPLAN_H
#define ROS_INTERFACE_MESSAGE_ROBOTPLAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/RobotTwist.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct RobotPlan_
{
  typedef RobotPlan_<ContainerAllocator> Type;

  RobotPlan_()
    : header()
    , twists()  {
    }
  RobotPlan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , twists(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ros_interface::RobotTwist_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_interface::RobotTwist_<ContainerAllocator> >> _twists_type;
  _twists_type twists;





  typedef boost::shared_ptr< ::ros_interface::RobotPlan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::RobotPlan_<ContainerAllocator> const> ConstPtr;

}; // struct RobotPlan_

typedef ::ros_interface::RobotPlan_<std::allocator<void> > RobotPlan;

typedef boost::shared_ptr< ::ros_interface::RobotPlan > RobotPlanPtr;
typedef boost::shared_ptr< ::ros_interface::RobotPlan const> RobotPlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::RobotPlan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::RobotPlan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::RobotPlan_<ContainerAllocator1> & lhs, const ::ros_interface::RobotPlan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.twists == rhs.twists;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::RobotPlan_<ContainerAllocator1> & lhs, const ::ros_interface::RobotPlan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::RobotPlan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::RobotPlan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::RobotPlan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::RobotPlan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::RobotPlan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::RobotPlan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::RobotPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b76360f7adf2338a7c5b793baf2bfa4";
  }

  static const char* value(const ::ros_interface::RobotPlan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b76360f7adf2338ULL;
  static const uint64_t static_value2 = 0xa7c5b793baf2bfa4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::RobotPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/RobotPlan";
  }

  static const char* value(const ::ros_interface::RobotPlan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::RobotPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     #  \n"
"RobotTwist[] twists #  \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/RobotTwist\n"
"Vector3   linear     # 线速度（x方向 y方向 z方向）\n"
"Vector3   angular     # 角速度（x方向 y方向 z方向）\n"
"string   action_name     # #简单指令，坐下，站起来（坐下，站起来指令直接运控执行），包含步态切换，规划只需要发送这个就行了\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Vector3\n"
"float32   x     #  \n"
"float32   y     #  \n"
"float32   z     #  \n"
;
  }

  static const char* value(const ::ros_interface::RobotPlan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::RobotPlan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.twists);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotPlan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::RobotPlan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::RobotPlan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "twists[]" << std::endl;
    for (size_t i = 0; i < v.twists.size(); ++i)
    {
      s << indent << "  twists[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_interface::RobotTwist_<ContainerAllocator> >::stream(s, indent + "    ", v.twists[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_ROBOTPLAN_H
