// Generated by gencpp from file ros_interface/TwistWithCovariance.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_TWISTWITHCOVARIANCE_H
#define ROS_INTERFACE_MESSAGE_TWISTWITHCOVARIANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_interface
{
template <class ContainerAllocator>
struct TwistWithCovariance_
{
  typedef TwistWithCovariance_<ContainerAllocator> Type;

  TwistWithCovariance_()
    : covariance()  {
    }
  TwistWithCovariance_(const ContainerAllocator& _alloc)
    : covariance(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _covariance_type;
  _covariance_type covariance;





  typedef boost::shared_ptr< ::ros_interface::TwistWithCovariance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::TwistWithCovariance_<ContainerAllocator> const> ConstPtr;

}; // struct TwistWithCovariance_

typedef ::ros_interface::TwistWithCovariance_<std::allocator<void> > TwistWithCovariance;

typedef boost::shared_ptr< ::ros_interface::TwistWithCovariance > TwistWithCovariancePtr;
typedef boost::shared_ptr< ::ros_interface::TwistWithCovariance const> TwistWithCovarianceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::TwistWithCovariance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::TwistWithCovariance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::TwistWithCovariance_<ContainerAllocator1> & lhs, const ::ros_interface::TwistWithCovariance_<ContainerAllocator2> & rhs)
{
  return lhs.covariance == rhs.covariance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::TwistWithCovariance_<ContainerAllocator1> & lhs, const ::ros_interface::TwistWithCovariance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::TwistWithCovariance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::TwistWithCovariance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::TwistWithCovariance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::TwistWithCovariance_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::TwistWithCovariance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::TwistWithCovariance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::TwistWithCovariance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e94311bfb2e686d923cb826b25755fa1";
  }

  static const char* value(const ::ros_interface::TwistWithCovariance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe94311bfb2e686d9ULL;
  static const uint64_t static_value2 = 0x23cb826b25755fa1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::TwistWithCovariance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/TwistWithCovariance";
  }

  static const char* value(const ::ros_interface::TwistWithCovariance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::TwistWithCovariance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] covariance #  \n"
;
  }

  static const char* value(const ::ros_interface::TwistWithCovariance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::TwistWithCovariance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TwistWithCovariance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::TwistWithCovariance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::TwistWithCovariance_<ContainerAllocator>& v)
  {
    s << indent << "covariance[]" << std::endl;
    for (size_t i = 0; i < v.covariance.size(); ++i)
    {
      s << indent << "  covariance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.covariance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_TWISTWITHCOVARIANCE_H
